version: '2'
services:

    jenkins:
        image: jenkins:2.32.3-alpine
        build: .
        volumes:
            - ./data:/var/jenkins_home
            - ./files/nodes/jenkins-slave:/var/jenkins_home/nodes/jenkins-slave
            - ./jenkins_tmp:/tmp
        ports:
            - "8081:8080"
            - "50000:50000"

    jenkins-slave:
        image: docker-slave
        build: ./slave
        depends_on:
            - jenkins
        volumes:
            - ./data_slave:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker:ro
            - ./slave_tmp:/tmp
        ports:
            - "9091:8080"

           